### ISSUE TITLE
a suggestion and powerful tool about wrapper for hms and gms

### ISSUE THREAD

**Issue by bengbeng00** [abusuioc/hms-gms-wrapper-location#3]
https://github.com/HMS-Core/hms-toolkit-convertor

This is a project on wrapper for hms and gms, and the corresponding toolkit namely plugin in Android Studio can be available.If your app project has integrate some gms kits like push, wallet, analytics, core, location, maps and so on, the plugin can transformor them from gms to hms, or from gms to gms+hms and another functions letting you integrate hms easiler. 

For example, the code fragment below is a result api generated by the plugin toolkit.
'''
/**
     * org.xms.f.iid.ExtensionInstanceId.getInstance(android.content.Context) Returns an instance of this class.<br/>
     * Support running environments including both HMS and GMS which are chosen by users.<br/>
     * Below are the references of HMS apis and GMS apis respectively:<br/>
     * com.huawei.hms.aaid.HmsInstanceId.getInstance(android.content.Context) : <a href="https://developer.huawei.com/consumer/en/doc/HMSCore-References-V5/hms-instanceid-0000001050255634-V5#EN-US_TOPIC_0000001050255634__section393712230274">https://developer.huawei.com/consumer/en/doc/HMSCore-References-V5/hms-instanceid-0000001050255634-V5#EN-US_TOPIC_0000001050255634__section393712230274</a><br/>
     * com.google.firebase.iid.FirebaseInstanceId.getInstance() : <a href="https://developers.google.com/android/reference/com/google/firebase/iid/FirebaseInstanceId#public-static-firebaseinstanceid-getinstance">https://developers.google.com/android/reference/com/google/firebase/iid/FirebaseInstanceId#public-static-firebaseinstanceid-getinstance</a><br/>
     *
     * @param context Context instance
     * @return ExtensionInstanceId instance
     */
    public static org.xms.f.iid.ExtensionInstanceId getInstance(android.content.Context context) {
        if (org.xms.g.utils.GlobalEnvSetting.isHms()) {
               ... // code fragment about hms logical
        } else {
               ... // code fragment about gms logical
        }
    }
'''

**Comment by abusuioc** [comment]
Thanks for the recommendation.
